name: crypto_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.1
  currency_text_input_formatter: ^2.1.7
  dartz: ^0.10.1
  device_info_plus: ^9.0.2
  device_preview: ^1.1.0
  dio: ^5.3.4
  envied: ^0.5.2
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.0
  flutter_flavor: ^3.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  get_it: ^7.6.0
  go_router: ^14.0.1
  injectable: ^2.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.7.0
  logger: ^2.0.2+1
  logging: ^1.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^6.0.5
  retrofit: ^4.0.3
  ua_client_hints: ^1.1.3
  visibility_detector: ^0.4.0+2


dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.5
  dart_code_linter: ^1.1.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  mocktail: ^1.0.1
  recase: ^4.1.0
  retrofit_generator: ^8.0.4
  sentry_dart_plugin: ^1.4.0
  test_api: ^0.6.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
